org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.172
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=whisperwaltz
mod_name=Whisperwaltz
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.whisperwaltz
mod_authors=Author
mod_description=Adds the Whisperwaltz sword - a blade that hums with spectral energy.
